import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //  <StoreProvider>
    <html lang="en">
      <body className="bg-black-100">
        <main className=" md:px-0 md:mx-auto min-h-screen min-w-screen flex flex-col justify-between overflow-x-hidden">
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
          </ThemeProvider>
        </main>
      </body>
    </html>
    // <ToastContainer
    //       position="top-right"
    //       autoClose={5000}
    //       hideProgressBar={false}
    //       newestOnTop={false}
    //       closeOnClick
    //       rtl={false}
    //       pauseOnFocusLoss
    //       draggable
    //       pauseOnHover
    //       theme="colored"
    //     />
    //  </StoreProvider>
  );
}
